---
title: "DATA607 Week 7 Assignment"
author: "Gabriel Campos"
date: "`r format(Sys.Date(), '%B %d %Y')`"
output: 
  html_document:
    includes:
      in_header: header.html
    css: ./lab.css
    highlight: pygments
    theme: cerulean
    toc: true
    toc_float: true
  pdf_document: default
editor_options: 
  chunk_output_type: console
---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(eval = TRUE, results = "hold")
library(tidyverse)
```

Overview
========

1. Pick three of your favorite books on one of your favorite subjects. 
    +At least one of the books should have more than one author. 
2. For each book, include the title, authors, and two or three other attributes that you find interesting.
3. Take the information that you’ve selected about these three books, and separately create three files which store the book’s information in HTML (using an html table), XML, and JSON formats (e.g. “books.html”, “books.xml”, and “books.json”).
4. To help you better understand the different file structures, I’d prefer that you create each of these files “by hand” unless you’re already very comfortable with the file formats.
5. Write R code, using your packages of choice, to load the information from each of the three sources into separate R data frames. Are the three data frames identical?
6. Your deliverable is the three source files and the R code.
    + If you can, package your assignment solution up into an .Rmd file and publish to rpubs.com. 
      * [This will also require finding a way to make your three text files accessible from the web].

Import Data
===========



Cleanup
=======

